#!/usr/bin/env bash
# Install the harness skill for the current user.
#
# - links this repository into every skills folder that exists
#   (~/.agents/skills is the cross-tool standard; ~/.claude, ~/.codex and
#   ~/.gemini are per-tool), creating ~/.agents/skills and ~/.claude/skills
#   when absent
# - links the bundled llm-wiki and obsidian-markdown into the same folders
#   where no copy of them is installed
# - writes a `harness` launcher to ~/.local/bin so prompts and playbooks need
#   no tool-specific path
# - with --with-graphify, installs the graphify CLI and its skill the official
#   way (uv tool install graphifyy && graphify install)
#
# Re-running is safe.
set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
WITH_GRAPHIFY=0
for arg in "$@"; do
  case "$arg" in
    --with-graphify) WITH_GRAPHIFY=1 ;;
    -h|--help) sed -n '2,12p' "$0"; exit 0 ;;
    *) echo "unknown option: $arg" >&2; exit 1 ;;
  esac
done

link_into() {  # link_into <skills-root> <name> <source>
  local root="$1" name="$2" src="$3" link
  link="$root/$name"
  mkdir -p "$root"
  if [ -L "$link" ]; then
    if [ "$(readlink "$link")" = "$src" ]; then
      echo "  ok        $link"
    else
      ln -sfn "$src" "$link"
      echo "  relinked  $link"
    fi
  elif [ -e "$link" ]; then
    echo "  kept      $link (real directory, not a link; left alone)"
  else
    ln -s "$src" "$link"
    echo "  linked    $link"
  fi
}

echo "harness install"

# skills roots: always ~/.agents/skills and ~/.claude/skills; the others only if the tool is present
ROOTS=("$HOME/.agents/skills" "$HOME/.claude/skills")
[ -d "$HOME/.codex" ] && ROOTS+=("$HOME/.codex/skills")
[ -d "$HOME/.gemini" ] && ROOTS+=("$HOME/.gemini/skills")

echo "skill:"
for root in "${ROOTS[@]}"; do
  link_into "$root" harness "$HERE"
done

# bundled skills (llm-wiki, obsidian-markdown), only where no copy exists at
# all. A real folder or a link to somewhere else (for example the owner's
# skills repository) counts as installed; only our own bundled link does not.
for name in llm-wiki obsidian-markdown; do
  have=""
  for root in "$HOME/.agents/skills" "$HOME/.claude/skills" "$HOME/.codex/skills" "$HOME/.gemini/skills"; do
    if [ -f "$root/$name/SKILL.md" ]; then
      if [ -L "$root/$name" ] && [ "$(readlink "$root/$name")" = "$HERE/bundled/$name" ]; then
        continue
      fi
      have="$root/$name"
    fi
  done
  if [ -n "$have" ]; then
    echo "$name: installed at $have (bundled copy at bundled/$name stays as fallback)"
  else
    echo "$name: not installed; linking the bundled copy"
    for root in "${ROOTS[@]}"; do
      link_into "$root" "$name" "$HERE/bundled/$name"
    done
  fi
done

# graphify is not bundled: its skill file is generated by its own CLI and the
# two are versioned together, so a static copy would drift. Opt in to install
# both the official way.
if [ "$WITH_GRAPHIFY" = 1 ]; then
  if command -v uv >/dev/null 2>&1; then
    echo "graphify: installing the CLI and its skill (uv tool install graphifyy && graphify install)"
    if uv tool install graphifyy && graphify install; then
      echo "graphify: installed"
    else
      echo "graphify: install did not finish; run the two commands by hand" >&2
    fi
  else
    echo "graphify: --with-graphify needs uv (https://docs.astral.sh/uv/); install uv, then re-run" >&2
  fi
fi

# launcher
BIN="$HOME/.local/bin"
mkdir -p "$BIN"
cat > "$BIN/harness" <<EOF
#!/usr/bin/env bash
exec python3 "$HERE/scripts/harness.py" "\$@"
EOF
chmod +x "$BIN/harness"
echo "launcher: $BIN/harness"
case ":$PATH:" in
  *":$BIN:"*) ;;
  *) echo "  note: $BIN is not on your PATH; add it, or prompts fall back to the python path" ;;
esac

command -v python3 >/dev/null || { echo "python3 is required" >&2; exit 1; }
python3 "$HERE/scripts/harness.py" index >/dev/null
echo
python3 "$HERE/scripts/harness.py" --project "$HERE" doctor || true
echo
echo "Start a new session in a project (Claude Code, Codex, Gemini CLI) and invoke the harness skill."
